spring.application.name=trade-validation-storage

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tradestorepgdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Server Configuration
server.port=8083
